nx = input('Digite valor de nx:')
ny = float(input('Digite valor de ny:'))
nz = bool(input('Digite valor de nz:'))
nw = bool(input('Digite valor de nw:'))
n1 = int(input('Digite valor de n1:'))
n2 = int(input('Digite valor de n2:'))
soma = n1 + n2
print('Tipo de nx é', type(nx), 'e valor', nx)
print('Tipo de ny é', type(ny), 'e valor', ny)
print('Tipo de nz é', type(nz), 'e valor', nz)
print('Tipo de nw é', type(nz), 'e valor', nw)
print('Tipo de n1 é', type(ny), 'e valor', n1)
print('Soma de {} e {} =  {}'.format(n1, n2, soma))
print('Nx pode ser número? ', nx.isnumeric())
print('Nx é alfabético? ', nx.isalpha())
